# R/scripts/fig_c_sensitivity.R
#
# Build the sensitivity figure for the dimension-adaptive coefficient c in
# delta = c log q across (alpha, sigma). For each cell (alpha, sigma) we
# invert median(lambda_min) at each q to find the required delta for target
# medians m0 in {0.1, 0.5, 1.0}, then fit delta = c log q + intercept across
# q to extract c.

suppressPackageStartupMessages({
  library(ggplot2)
  library(gridExtra)
  library(grid)
})

PROJECT_ROOT <- Sys.getenv("SPIKESLAB_ROOT", unset = getwd())
IN_RDS <- file.path(PROJECT_ROOT, "R", "results", "c_sensitivity.rds")
OUT_PDF <- file.path(PROJECT_ROOT, "figures", "c_sensitivity.pdf")
OUT_TABLE <- file.path(PROJECT_ROOT, "tables", "c_sensitivity.tex")

obj <- readRDS(IN_RDS)
tab <- obj$summary
# Drop cells with too few accepted draws for stable median (need ~50+).
tab$reliable <- tab$n_accepted >= 50L
tab <- tab[order(tab$alpha, tab$sigma, tab$q, tab$delta), ]

# Extract c(m0) per (alpha, sigma) by:
#   1. for each q, invert median(lambda_min)(delta) at the four sampled deltas
#      to find delta_req(q) such that median = m0.
#   2. fit delta_req(q) ~ c * log q + intercept; report slope c.
TARGETS <- c(0.1, 0.5, 1.0)

extract_c <- function(sub, target) {
  q_vals <- sort(unique(sub$q))
  delta_req <- numeric(length(q_vals))
  for (i in seq_along(q_vals)) {
    cell <- sub[sub$q == q_vals[i] & sub$reliable, ]
    if (nrow(cell) < 3L) { delta_req[i] <- NA_real_; next }
    cell <- cell[order(cell$delta), ]
    d <- cell$delta; m <- cell$median
    # If even the smallest delta already meets the target, set delta_req = d[1]
    if (m[1] >= target) { delta_req[i] <- d[1]; next }
    if (max(m) < target) { delta_req[i] <- NA_real_; next }
    f <- splinefun(d, m, method = "monoH.FC")
    delta_req[i] <- uniroot(function(x) f(x) - target, c(d[1], d[length(d)]))$root
  }
  ok <- !is.na(delta_req)
  if (sum(ok) < 3L) return(list(c = NA_real_, intercept = NA_real_,
                                 n = sum(ok), q_vals = q_vals,
                                 delta_req = delta_req))
  fit <- lm(delta_req[ok] ~ log(q_vals[ok]))
  list(c = unname(coef(fit)[2]), intercept = unname(coef(fit)[1]),
       n = sum(ok), q_vals = q_vals, delta_req = delta_req)
}

c_rows <- list()
req_rows <- list()
for (alpha in sort(unique(tab$alpha))) {
  for (sigma in sort(unique(tab$sigma))) {
    sub <- tab[tab$alpha == alpha & tab$sigma == sigma, ]
    for (target in TARGETS) {
      r <- extract_c(sub, target)
      c_rows[[length(c_rows) + 1L]] <- data.frame(
        alpha = alpha, sigma = sigma, target = target,
        c = r$c, intercept = r$intercept, n_q = r$n,
        stringsAsFactors = FALSE)
      for (i in seq_along(r$q_vals)) {
        req_rows[[length(req_rows) + 1L]] <- data.frame(
          alpha = alpha, sigma = sigma, target = target,
          q = r$q_vals[i], delta_req = r$delta_req[i],
          stringsAsFactors = FALSE)
      }
    }
  }
}
c_df <- do.call(rbind, c_rows)
req_df <- do.call(rbind, req_rows)
req_df <- req_df[!is.na(req_df$delta_req), ]

# Reshape c_df to wide for a clean table: rows = (alpha, sigma), cols = target.
c_wide <- reshape(c_df[, c("alpha", "sigma", "target", "c")],
                  idvar = c("alpha", "sigma"),
                  timevar = "target", direction = "wide")
names(c_wide) <- gsub("c\\.", "c_m", names(c_wide))

# LaTeX table (drop the m=1.0 column since all NA in the sweep).
{
  lines <- c(
    "% c-sensitivity table generated by fig_c_sensitivity.R",
    "\\begin{tabular}{ccccc}",
    "\\toprule",
    "$\\alpha$ & $\\sigma$ & $c$ at $m_0=0.1$ & $c$ at $m_0=0.5$ \\\\",
    "\\midrule"
  )
  for (i in seq_len(nrow(c_wide))) {
    row <- c_wide[i, ]
    fmt <- function(x) {
      if (is.na(x)) return("---")
      v <- if (abs(x) < 0.005) 0 else x
      sprintf("%.2f", v)
    }
    lines <- c(lines,
               sprintf("%g & %g & %s & %s \\\\",
                       row$alpha, row$sigma,
                       fmt(row$c_m0.1), fmt(row$c_m0.5)))
  }
  lines <- c(lines, "\\bottomrule", "\\end{tabular}")
  writeLines(lines, OUT_TABLE)
}

# Figure: facet by (alpha, sigma); plot median(lambda_min) vs q for each
# delta, with horizontal target lines. Use parseable strings so label_parsed
# renders both labels as math.
plot_df <- tab[tab$reliable, ]
plot_df$alpha_val <- factor(plot_df$alpha, levels = c(1, 3),
                             labels = c("alpha == 1", "alpha == 3"))
plot_df$sigma_val <- factor(plot_df$sigma, levels = c(0.3, 1, 3),
                             labels = c("sigma == 0.3", "sigma == 1", "sigma == 3"))
plot_df$delta_factor <- factor(sprintf("delta=%g", plot_df$delta),
                                levels = c("delta=0", "delta=0.5",
                                           "delta=1", "delta=2"))

palette_delta <- c("delta=0"   = "#969696",
                   "delta=0.5" = "#a6cee3",
                   "delta=1"   = "#1f78b4",
                   "delta=2"   = "#33a02c")
labels_delta <- c("delta=0"   = expression(delta == 0),
                  "delta=0.5" = expression(delta == 0.5),
                  "delta=1"   = expression(delta == 1),
                  "delta=2"   = expression(delta == 2))

theme_paper <- theme_minimal(base_size = 9) +
  theme(
    legend.position    = "bottom",
    legend.title       = element_text(size = 8),
    panel.grid.minor   = element_blank(),
    strip.background   = element_blank(),
    strip.text         = element_text(size = 9, face = "plain"),
    plot.title         = element_text(size = 9, face = "plain")
  )

fig_A <- ggplot(plot_df,
              aes(x = q, y = median, colour = delta_factor, group = delta_factor)) +
  geom_hline(yintercept = TARGETS, linetype = "dashed", colour = "grey60") +
  geom_line() +
  geom_point(size = 1.5) +
  facet_grid(alpha_val ~ sigma_val, labeller = label_parsed) +
  scale_x_continuous(breaks = c(5, 10, 20, 30, 50)) +
  scale_y_log10() +
  scale_colour_manual(values = palette_delta, name = NULL,
                      labels = labels_delta) +
  labs(x = "q",
       y = expression("median  " * lambda[min] * "(K) given PD"),
       title = "A. Median lambda_min vs q for each (alpha, sigma) and delta") +
  theme_paper

# Verification panel: for each (alpha, sigma, target) with extracted c, plot
# the interpolated median at delta = c * log q against q. If c captures a
# constant log-linear slope of the required delta, this curve sits flat at
# the target.
verify_rows <- list()
for (i in seq_len(nrow(c_df))) {
  row <- c_df[i, ]
  if (is.na(row$c)) next
  sub_grid <- tab[tab$alpha == row$alpha & tab$sigma == row$sigma & tab$reliable, ]
  for (q_val in sort(unique(sub_grid$q))) {
    cell <- sub_grid[sub_grid$q == q_val, ]
    if (nrow(cell) < 3L) next
    cell <- cell[order(cell$delta), ]
    delta_target <- row$c * log(q_val)
    if (delta_target < min(cell$delta) || delta_target > max(cell$delta)) {
      med <- NA_real_
    } else {
      f <- splinefun(cell$delta, cell$median, method = "monoH.FC")
      med <- as.numeric(f(delta_target))
    }
    verify_rows[[length(verify_rows) + 1L]] <- data.frame(
      alpha = row$alpha, sigma = row$sigma, target = row$target,
      q = q_val, delta_target = delta_target, median_at_rule = med,
      stringsAsFactors = FALSE)
  }
}
verify_df <- do.call(rbind, verify_rows)
verify_df <- verify_df[!is.na(verify_df$median_at_rule), ]
verify_df$alpha_val <- factor(verify_df$alpha, levels = c(1, 3),
                               labels = c("alpha == 1", "alpha == 3"))
verify_df$sigma_val <- factor(verify_df$sigma, levels = c(0.3, 1, 3),
                               labels = c("sigma == 0.3", "sigma == 1", "sigma == 3"))
verify_df$target_label <- factor(sprintf("m == %.1f", verify_df$target),
                                  levels = c("m == 0.1", "m == 0.5", "m == 1.0"))
palette_target <- c("m == 0.1" = "#1b9e77",
                    "m == 0.5" = "#d95f02",
                    "m == 1.0" = "#7570b3")

fig_B <- ggplot(verify_df,
                aes(x = q, y = median_at_rule, colour = target_label,
                    group = target_label)) +
  geom_hline(aes(yintercept = target, colour = target_label),
             linetype = "dashed", alpha = 0.5) +
  geom_line() +
  geom_point(size = 1.6) +
  facet_grid(alpha_val ~ sigma_val, labeller = label_parsed) +
  scale_x_continuous(breaks = c(5, 10, 20, 30, 50)) +
  scale_y_log10() +
  scale_colour_manual(values = palette_target, name = NULL,
                      labels = c(expression(m[0] == 0.1),
                                 expression(m[0] == 0.5),
                                 expression(m[0] == 1.0))) +
  labs(x = "q",
       y = expression("median  " * lambda[min] * " at  " * delta == c %.% log(q)),
       title = "B. Verification: median at the extracted delta = c log q") +
  theme_paper

fig <- gridExtra::grid.arrange(fig_A, fig_B, ncol = 1, heights = c(1, 1))
ggplot2::ggsave(OUT_PDF, plot = fig, width = 9.5, height = 9, units = "in")
cat(sprintf("Wrote %s\n", OUT_PDF))
cat(sprintf("Wrote %s\n", OUT_TABLE))

cat("\nExtracted c values (rows = (alpha, sigma), cols = targets):\n")
print(c_wide, row.names = FALSE)
